<?php
$this->headScript()->appendFile($this->basePath('/js/oferty.js'));
$form->setAttribute('action', $this->url('nieruchomosci/koszyk', []))
?>

<?= $this->form()->openTag($form) ?>

<h2 class="my-3">Mój koszyk</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th><?= $form->get('typ_oferty')->getLabel() ?></th>
            <th><?= $form->get('typ_nieruchomosci')->getLabel() ?></th>
            <th><?= $form->get('numer')->getLabel() ?></th>
            <th><?= $form->get('powierzchnia')->getLabel() ?></th>
            <th><?= $form->get('cena')->getLabel() ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($koszyk as $of): ?>
            <tr>
                <td><?= $of->id ?></td>
                <td><?= $of->typ_oferty ?></td>
                <td><?= $of->typ_nieruchomosci ?></td>
                <td><?= $of->numer ?></td>
                <td><?= $of->powierzchnia ?></td>
                <td><?= $of->cena ?></td>
                <td>
                    <a href="<?= $this->url('nieruchomosci/oferty', ['action' => 'szczegoly', 'id' => $of->id]) ?>" title="szczegóły"><i class="fas fa-folder-open"></i></a>&nbsp;
                    <a href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'usun', 'id' => $of->id]) ?>" title="usun z koszyka" class="aUsunZKoszyka"><i class="fas fa-shopping-cart"></i></a>&nbsp;
                    <a href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukuj', 'id' => $of->id]) ?>" title="drukuj"><i class="fas fa-print"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody> 
	<td>
	<a href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'drukuj_caly', 'id' => $of->id]) ?>" title="drukuj cala zawartosc koszyka"><i class="fas fa-print"></i></a>
	</td>
</table>

<?= $this->paginationControl(
    $koszyk,
    'sliding', 
    ['partial/paginator.phtml', 'Nieruchomosci'], 
    ['route' => 'nieruchomosci/koszyk', 'parametry' => $parametry]
)
?>

<?= $this->form()->closeTag($form); ?>