<h1><?= $tytul ?></h1>


<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label"><?= $this->formLabel($form->get('imie')) ?></label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail"<?= $this->formText($form->get('imie')) ?>
    </div>

   <label for="Autor" class="col-sm-2 col-form-label"><?= $this->formLabel($form->get('nazwisko')) ?></label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="Autor"<?= $this->formText($form->get('nazwisko')) ?>
    </div>
</div>