<?php
$this->headScript()->appendFile($this->basePath('/js/zapytanie.js'));


$zapytanie = new \Laminas\Form\Element\Textarea('zapytanie');
$zapytanie->setAttributes(['rows' => 5]);
$zapytanie->setValue("Proszę o podanie szczegółów oferty numer $oferta[numer].");

?>

<h2>Szczegóły oferty <?= $oferta->numer ?></h2>

<p>
	<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#Zapytanie_button">
		Wyślij zapytanie
	</button>
</p>

<div class="modal fade" id="Zapytanie_button" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Zapytanie ofertowe</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form method="post" action="<?= $this->url('nieruchomosci/zapytanie', ['action' => 'wyslij'], null, true) ?>" id="formZapytanie">
					<?= $this->formElement($zapytanie) ?>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" id="btnWyslij">Wyślij</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
			</div>
		</div>
	</div>
</div>